---
# tasks file for keepalived

- name: Install keepalived
  apt: name=keepalived state=latest

- block:

  - name: Generate Keepalived config file
    template: src=keepalived.j2 dest={{ destin_folder }}/keepalived.conf mode=0644
    vars:
      name_server: pi1
      state: MASTER
      priority: 100

  when: ansible_all_ipv4_addresses == ['192.168.31.81']

- block:

  - name: Generate Keepalived config file
    template: src=keepalived.j2 dest={{ destin_folder }}/keepalived.conf mode=0644
    vars:
      name_server: pi2
      state: BACKUP
      priority: 200

  when: ansible_all_ipv4_addresses == ['192.168.31.216']

- name: Start Keepalived
  service: name=keepalived state=started enabled=yes
  
